### PR TITLE
Misc: allow unknown args when finding prefix

### PR DESCRIPTION
**Pull request by aarani**

### CODE REVIEW

**Comment by knocte** [comment]
I shouldn't have merged it because you were missing the **why**, sigh. Please write the **why** here.

**Comment by knocte** [comment]
ping

**Comment by aarani** [comment]
> I shouldn't have merged it because you were missing the **why**, sigh. Please write the **why** here.

There's no reason for a code that's supposed to search arguments for a prefix, to limit or even care about other arguments,
this commit fixes that.

**Comment by aarani** [comment]
> > There's no reason for a code that's supposed to search arguments for a prefix, to limit or even care about other arguments, this commit fixes that.
> 
> And why do you need it to not care about other arguments? Please state the **ultimate why** @aarani

edited*

**Pull request merged**
