### PR TITLE
Tests: moved tests from testTsv.fs to unit tests

### PR DESCRIPTION
**Pull request by webwarrior-ws**
Reorganized tests from testTsv.fs file as unit tests in Fsdk.Tests project.

### CODE REVIEW

**Comment by knocte** [comment]
@webwarrior-ws good work; I might leave this open for a bit until I double-check if other tests need to be moved or not.

In the meantime, if you finish the NOnion&geewallet PRs to adopt Fsdk's FSharpUtil, next thing to do would be to create a PR in this fsx repo to remove all Async.RunSynchronously calls from Fsdk (the consequence of this is that some functions will start returning `Async<Foo>` instead of `Foo`, and the side-effect is that you might need to change some scripts that make use of this functions to call Async.RunSynchronously in them.

Thanks

**Comment by knocte** [comment]
@webwarrior-ws let's move the AsyncCancellation tests from geewallet to this PR too please. I think I created them when I was working on some AsyncExtensions functions, so they should belong here.

**Comment by knocte** [comment]
> New changes since you last viewed
> Merge branch 'nblockchain:master' into move-tsv-test

What is this? Please don't push merge commits to PRs.

**Comment by knocte** [comment]
> What is this? Please don't push merge commits to PRs.

Rebasing PRs needs to be done with `git rebase` or `git cherry-pick`, not `git merge`.

**Comment by knocte** [comment]
> Rebasing PRs needs to be done with git rebase or git cherry-pick, not git merge.

On top of that, I never asked you to rebase this PR, so please don't rebase when it's not necessary.

**Comment by webwarrior-ws** [comment]
Reverted that merge. I think merge occurred because I clicked "sync fork" on github.

**Pull request merged**
